
function valid1() returns integer {
    return 0;
}

function valid2() returns integer {
    if( 1 == 1 ) {
        return 0;
    } else
    if( 2 == 2 ) {
        
        if ( 4 == 4 ) {
            const integer x = 5;

            if( x > 6) {
                {
                    return 0;
                }
            } else
            if ( x > 7 ) {
                return 1;
            }
            else
                return 0;

        } else {
            return 0;
        }
    } else
        return 0;
}

// main invalid
procedure main() returns integer {
    if( 1 == 1 ) {
        return 0;
    } else
    if( 2 == 2 ) {
        
        if ( 4 == 4 ) {
            const integer x = 5;

            if( x > 6) {
                {
                    return 0;
                }
            } else
            if ( x > 7 ) {
                // This path is where the error occurs.
                // According to the Discord server question about returns in loops,
                // this is actually undecidable. We do not assume the loop always executes
                // hence this path has no return.
                loop {
                    return 0;
                }
            }
            else
                return 0;

        } else {
            return 0;
        }
    } else
        return 0;
}
// CHECK:ReturnError on Line 34
